- name: create facts directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0755

- name: create redis facts
  template:
    src: etc/ansible/facts.d/redis.fact.j2
    dest: /etc/ansible/facts.d/redis.fact

- name: create redis instance facts
  template:
    src: etc/ansible/facts.d/redis_instance.fact.j2
    dest: /etc/ansible/facts.d/redis_{{ redis_port }}.fact
    mode: 0755
  when: not redis_sentinel

- name: create redis sentinel facts
  template:
    src: etc/ansible/facts.d/redis_instance.fact.j2
    dest: /etc/ansible/facts.d/redis_sentinel_{{ redis_sentinel_port }}.fact
    mode: 0755
  when: redis_sentinel
